add tests for book and category(repository,services,controllers)
mykhailoKrlKrk/book-store pull request #15
Opened 2023-09-24 09:58 UTC by mykhailoKrlKrk

test coverage : 
<img width="798" alt="Знімок екрана 2023-09-24 о 12 57 27" src="https://github.com/mykhailoKrlKrk/book-store/assets/133024859/f8d9686c-82c2-4e94-8342-3cdb81f64c4d"><img width="821" alt="Знімок екрана 2023-09-24 о 12 57 11" src="https://github.com/mykhailoKrlKrk/book-store/assets/133024859/5d71b06d-8218-414e-97e9-c5f7893a59c4">

2023-09-24 17:01 UTC, Ivan95kos requested changes
Привіт, дивиться дуже сильно, тільки я б рекомендував тобі під кожен метод створювати свої SQL скрипти, щоб вони були незалежні. Ідентифікатори моделей не мають повторюватися від теста до теста.
Тому що будь які зміни у скрипті або коді і деякі тести будь падати це в кращому випадку.

Тому створи таку ж саму структуру для SQL файлів як і у тестових класах які ти тестуєш, плюс пакет з назвою тестового класу і в ньому будеш створювати всі скрипти які відносяться до тестового класу.

Якщо потрібно більше деталей або щось пояснити стосовно цього пиши у чаті буду відповідати.

2023-09-24 17:01 UTC, Ivan95kos commented on src/main/java/mate/academy/book/store/service/book/CategoryServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find category by i:" + id));
```suggestion
                () -> new EntityNotFoundException("Can't find category by id: " + id));
```

2023-09-24 17:01 UTC, Ivan95kos commented on src/main/java/mate/academy/book/store/service/book/CategoryServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find category by i:" + id));
```suggestion
                () -> new EntityNotFoundException("Can't find category by id: " + id));
```

2023-09-26 16:29 UTC, Ivan95kos requested changes
Привіт, бачу що ти спершу додав sql файли, а після видалив.
Я мав наувазі щоб ти зробив наступне:
в пакеті `test/resources` створив нові підпакети такі як у проекті.
Наприклад для тестування `BookControllerTest` в тебе має бути такий набір пакетів:`
mate/academy/book/store/controllers/BookControllerIntegrationTest` 
В цьому пакеті `BookControllerIntegrationTest` додаєш всі `SQL` скриптти які потрібно для тестування методів, приклад як їх називати я тобі в коментарях залишив.
В загальному в тебе має бути твої тестові методи помножені на два, скільки в середньому `SQL` скриптів мало б бути.
Можеш добавляти загальні скрипти но це в основному дані які не змінються після викононна методу і мають залишитися для всіх тестових методів однаковими.

Також до інтеграцінийх тестів краще добвляти слово `Integration` в назву тестуємого класу.

2023-09-26 16:29 UTC, Ivan95kos commented on src/test/java/mate/academy/book/store/controllers/BookControllerTest.java
> +            "classpath:database/books/create-books-with-categories.sql",
```suggestion
            "classpath:database/books/before_ getAllBooks_ReturnListOfExistingBooks.sql",
```

2023-09-26 16:29 UTC, Ivan95kos commented on src/test/java/mate/academy/book/store/controllers/BookControllerTest.java
> +            "classpath:database/books/delete-all-books.sql"
```suggestion
            "classpath:database/books/after_ getAllBooks_ReturnListOfExistingBooks.sql"
```

2023-09-26 16:29 UTC, Ivan95kos commented on src/test/java/mate/academy/book/store/controllers/BookControllerTest.java
> +public class BookControllerTest {
```suggestion
public class BookControllerIntegrationTest {
```

2023-09-27 11:05 UTC, olekskov commented on src/test/resources/database/books/after/after_ getAllBooks_ReturnListOfExistingBooks.sql
when you have such amount of files they should have same package system as tests in order to be able to match them
with current package I cannot understand which test this file belongs to src/test/resources/database/books/after/after_ getAllBooks_ReturnListOfExistingBooks.sql

should be something like
src/test/resources/controllers/BookControllerIntegrationTest/after/after_ getAllBooks_ReturnListOfExistingBooks.sql

Please recheck all files

2023-09-27 17:09 UTC, Ivan95kos approved these changes
Чудова робота)

2023-09-27 21:55 UTC, merged